
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Ifan
 */
public class Frame5 extends javax.swing.JFrame {

    /**
     * Creates new form Frame5
     */
    public Frame5() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        tsetor = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        awal = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        takhir = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("PENYETORAN");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(130, 10, 160, 30);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "SETOR", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N
        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Rp");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(20, 20, 17, 30);
        jPanel1.add(tsetor);
        tsetor.setBounds(50, 20, 310, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 50, 380, 70);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "SALDO AWAL", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N
        jPanel2.setLayout(null);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Rp");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(20, 20, 17, 30);
        jPanel2.add(awal);
        awal.setBounds(50, 20, 310, 30);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(10, 130, 380, 60);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "SALDO AKHIR", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N
        jPanel3.setLayout(null);

        takhir.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel3.add(takhir);
        takhir.setBounds(50, 20, 310, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Rp");
        jPanel3.add(jLabel5);
        jLabel5.setBounds(20, 20, 17, 30);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(10, 200, 380, 60);

        jButton1.setText("SELESAI");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(70, 280, 110, 30);

        jButton2.setText("KEMBALI");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(235, 280, 110, 30);

        setBounds(0, 0, 416, 365);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String str = tsetor.getText();
        String ahr = takhir.getText();
        boolean huruf = false;
        int setor = 0;
        int akhir = 0;
        float nmr;
        
        try {
            nmr = Float.parseFloat(str);
        }
        catch (NumberFormatException e) {
            huruf = true;
        }
        
        if (huruf) {
            JOptionPane.showMessageDialog(null, "Data diisi dengan Angka");
            setor = Integer.parseInt(str);
            akhir = Integer.parseInt(ahr);
        }
        
     
        if (tsetor.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Data Harus Diisi");
        } else if (setor > akhir){
                      JOptionPane.showMessageDialog(null, "Saldo Anda tidak mencukupi");
        }
        


else{
        
        int h1 = Integer.parseInt(tsetor.getText());
        int q2 = Integer.parseInt(awal.getText());
        int x = h1+q2;   
        
        takhir.setText(String.valueOf(x));
       
     // TODO add your handling code here:
    }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Frame2 fm;
        fm = new Frame2();
        fm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame5().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField awal;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel takhir;
    private javax.swing.JTextField tsetor;
    // End of variables declaration//GEN-END:variables
}
